version: '3.9'
services:
  cache:
    image: redis:alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes: 
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
  postgres:
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=go-chat
    networks:
      - backend 
  omachat-api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8085:8085"
    environment:
      - DB_SOURCE=postgresql://root:test@postgres:5430/go-chat?sslmode=disable
      - CACHE_SOURCE=redis:6379
    depends_on:
      - postgres
      - cache
    networks:
      - backend
networks:
  backend:




  